### PR TITLE
Rename to go-libdht

### PR DESCRIPTION
**Pull request by guillaumemichel**

### CODE REVIEW

**Comment by guillaumemichel** [comment]
@iand should I rename `KademliaEvent` to `DhtEvent` or is this type specific to Kademlia?

https://github.com/plprobelab/go-kademlia/blob/183fa8f01f8792c606cec82cad922c08df2dd154/coord/coordinator.go#L505

**Comment by iand** [comment]
> @iand should I rename `KademliaEvent` to `DhtEvent` or is this type specific to Kademlia?
> 
> https://github.com/plprobelab/go-kademlia/blob/183fa8f01f8792c606cec82cad922c08df2dd154/coord/coordinator.go#L505

I think we can remove the coord package entirely. There is an improved version in go-libp2p-kad-dht/v2

**Comment by iand** [comment]
It may be better to create a new repository for go-libdht and migrate the issues that apply only to rethinking the dht as a whole.

**Comment by dennis-tra** [comment]
> It may be better to create a new repository for go-libdht and migrate the issues that apply only to rethinking the dht as a whole.

We'd also have a chance to decrease the repo size by **not** migrating some of the blobs that are checked in (or at least decrease their size)

**Pull request closed without merging**
